name: m
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  dio: ^5.9.0
  go_router: ^16.2.0
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  pretty_dio_logger: ^1.4.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #       - asset: fonts/TrajanPro.ttf
